#define COLLIDER_Root           0x42
#define COLLIDER_Box6           0x41
#define COLLIDER_Box5           0x40
#define COLLIDER_Box4           0x3F
#define COLLIDER_Boz3           0x3E
#define COLLIDER_Box2           0x3D
#define COLLIDER_Box1           0x3C
#define COLLIDER_ItemStand      0x3B
#define COLLIDER_CheatoStand    0x3A
#define COLLIDER_Reports        0x39
#define COLLIDER_StarPost3      0x38
#define COLLIDER_StarPost2      0x37
#define COLLIDER_StarPost1      0x36
#define COLLIDER_yoko_ushiro    0x35
#define COLLIDER_syoumen        0x34
#define COLLIDER_InnStand       0x33
#define COLLIDER_g58            0x32
#define COLLIDER_kanban         0x31
#define COLLIDER_o270           0x30
#define COLLIDER_o154           0x2F
#define COLLIDER_bar_inn        0x2E
#define COLLIDER_o244           0x2D
#define COLLIDER_o110           0x2C
#define COLLIDER_o126           0x2B
#define COLLIDER_table          0x2A
#define COLLIDER_o92            0x29
#define COLLIDER_o90            0x28
#define COLLIDER_o185           0x27
#define COLLIDER_deilit1u       0x26
#define COLLIDER_harbour_club   0x25
#define COLLIDER_o291           0x24
#define COLLIDER_deili1         0x23
#define COLLIDER_o48            0x22
#define COLLIDER_deilit1        0x21
#define COLLIDER_g56            0x20
#define COLLIDER_o256k          0x1F
#define COLLIDER_o236           0x1E
#define COLLIDER_kameki         0x1D
#define COLLIDER_o184           0x1C
#define COLLIDER_o183           0x1B
#define COLLIDER_o193k          0x1A
#define COLLIDER_o13            0x19
#define COLLIDER_o190k          0x18
#define COLLIDER_o189k          0x17
#define COLLIDER_tt9            0x16
#define COLLIDER_kujira         0x15
#define COLLIDER_o186           0x14
#define COLLIDER_o50            0x13
#define COLLIDER_Default        0x12
#define COLLIDER_kujira_atari   0x11
#define COLLIDER_o264           0x10
#define COLLIDER_sign           0xF
#define COLLIDER_o212           0xE
#define COLLIDER_deilit9        0xD
#define COLLIDER_o187           0xC
#define COLLIDER_o182           0xB
#define COLLIDER_o181           0xA
#define COLLIDER_kaimen         0x9
#define COLLIDER_o206           0x8
#define COLLIDER_o36            0x7
#define COLLIDER_g1             0x6
#define COLLIDER_EntryBarricade 0x5
#define COLLIDER_deilitne       0x4
#define COLLIDER_deiline        0x3
#define COLLIDER_o115           0x2
#define COLLIDER_o107           0x1
#define COLLIDER_o106           0x0

#define ZONE_Root               0xE
#define ZONE_g34                0xD
#define ZONE_o186               0xC
#define ZONE_g33                0xB
#define ZONE_west               0xA
#define ZONE_harbour_club       0x9
#define ZONE_bar_inn            0x8
#define ZONE_o85                0x7
#define ZONE_Default            0x6
#define ZONE_kaimen             0x5
#define ZONE_o50                0x4
#define ZONE_o48                0x3
#define ZONE_g1                 0x2
#define ZONE_o106               0x1
#define ZONE_bero               0x0

